# Generated by Django 3.0.4 on 2020-10-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractPainting',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cancelled_price', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=2000)),
                ('small_description', models.TextField(max_length=2000)),
                ('specifications', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='InkPainting',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cancelled_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('small_description', models.TextField(max_length=2000)),
                ('specifications', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PastelPainting',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cancelled_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('small_description', models.TextField(max_length=2000)),
                ('specifications', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='WildlifePainting',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cancelled_price', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=2000)),
                ('small_description', models.TextField(max_length=2000)),
                ('specifications', models.TextField(max_length=2000)),
            ],
        ),
    ]
