# Generated by Django 3.1 on 2020-09-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0002_auto_20200910_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractpainting',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
