# Generated by Django 3.1 on 2020-09-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0003_abstractpainting_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractpainting',
            old_name='integer',
            new_name='cancelled_price',
        ),
        migrations.AddField(
            model_name='abstractpainting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
