# Generated by Django 3.1 on 2020-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0004_auto_20200911_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractpainting',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
