# Generated by Django 3.1 on 2020-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0005_abstractpainting_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractpainting',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
