# Generated by Django 3.1 on 2020-09-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0006_abstractpainting_small_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcrylicPainting',
            new_name='WildlifePainting',
        ),
    ]
