# Generated by Django 3.1 on 2020-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0007_auto_20200912_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildlifepainting',
            old_name='integer',
            new_name='cancelled_price',
        ),
        migrations.AddField(
            model_name='wildlifepainting',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifepainting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wildlifepainting',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifepainting',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
