# Generated by Django 3.1 on 2020-09-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0008_auto_20200912_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cancelled_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
