# Generated by Django 3.1 on 2020-09-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
