# Generated by Django 3.1.1 on 2020-09-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicnav', '0011_auto_20200921_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inkpainting',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='inkpainting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inkpainting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inkpainting',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='inkpainting',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='pastelpainting',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='pastelpainting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pastelpainting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pastelpainting',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='pastelpainting',
            name='specifications',
        ),
    ]
