# Generated by Django 3.1.1 on 2020-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madhubani',
            fields=[
                ('painting_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('small_description', models.TextField(max_length=2000)),
                ('specifications', models.TextField(max_length=2000)),
            ],
        ),
    ]
