# Generated by Django 3.1.1 on 2020-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='i_id',
            field=models.CharField(max_length=100000000),
        ),
    ]
