# Generated by Django 3.1.1 on 2020-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floating',
            old_name='id',
            new_name='painting_id',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='id',
            new_name='painting_id',
        ),
        migrations.RenameField(
            model_name='modern',
            old_name='id',
            new_name='painting_id',
        ),
        migrations.RenameField(
            model_name='tabletop',
            old_name='id',
            new_name='painting_id',
        ),
        migrations.AddField(
            model_name='deepset',
            name='cancelled_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepset',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deepset',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepset',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deepset',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floating',
            name='cancelled_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floating',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floating',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floating',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floating',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='cancelled_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modern',
            name='cancelled_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modern',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modern',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modern',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modern',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletop',
            name='cancelled_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabletop',
            name='description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletop',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabletop',
            name='small_description',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletop',
            name='specifications',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deepset',
            name='painting_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
