# Generated by Django 3.1.1 on 2020-09-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forposters', '0002_auto_20200921_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignposters',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='campaignposters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaignposters',
            name='price',
        ),
        migrations.RemoveField(
            model_name='campaignposters',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='campaignposters',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='corporateposters',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='corporateposters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='corporateposters',
            name='price',
        ),
        migrations.RemoveField(
            model_name='corporateposters',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='corporateposters',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='politicalposters',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='politicalposters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='politicalposters',
            name='price',
        ),
        migrations.RemoveField(
            model_name='politicalposters',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='politicalposters',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='showposters',
            name='cancelled_price',
        ),
        migrations.RemoveField(
            model_name='showposters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='showposters',
            name='price',
        ),
        migrations.RemoveField(
            model_name='showposters',
            name='small_description',
        ),
        migrations.RemoveField(
            model_name='showposters',
            name='specifications',
        ),
    ]
