# Generated by Django 3.1.1 on 2020-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forposters', '0004_auto_20200921_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateposters',
            old_name='id',
            new_name='poster_id',
        ),
        migrations.RenameField(
            model_name='politicalposters',
            old_name='id',
            new_name='poster_id',
        ),
        migrations.RenameField(
            model_name='showposters',
            old_name='id',
            new_name='poster_id',
        ),
        migrations.RemoveField(
            model_name='campaignposters',
            name='painting_id',
        ),
        migrations.AddField(
            model_name='campaignposters',
            name='poster_id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
